# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lane going to execute tests."
  lane :tests do
    run_tests(scheme: "FlightComputerTests",
            )
  end

  desc "Sync signing"
  lane :signing do
    app_store_connect_api_key
    sync_code_signing(
      readonly: true
    )
  end

  desc "Build binary"
  lane :build do
    signing
    gym(scheme: "FlightComputer")
  end

  lane :beta do
    build
    upload_to_testflight
  end
end
